import {
  Award,
  BookOpen,
  Briefcase,
  Building2,
  Calendar,
  CheckCircle2,
  ClipboardList,
  Clock,
  FlaskConical,
  Globe,
  GraduationCap,
  Handshake,
  HeartPulse,
  Landmark,
  Layers,
  Library,
  Lightbulb,
  MapPin,
  Megaphone,
  Monitor,
  Palette,
  Phone,
  PiggyBank,
  School,
  ShieldCheck,
  Stethoscope,
  Trophy,
  UserCheck,
  Users,
  Wrench,
  type LucideIcon,
} from "lucide-react";

export const iconOptions: Record<string, LucideIcon> = {
  school: School,
  graduationCap: GraduationCap,
  bookOpen: BookOpen,
  library: Library,
  users: Users,
  userCheck: UserCheck,
  briefcase: Briefcase,
  building: Building2,
  landmark: Landmark,
  clipboardList: ClipboardList,
  checkCircle: CheckCircle2,
  shieldCheck: ShieldCheck,
  calendar: Calendar,
  clock: Clock,
  mapPin: MapPin,
  phone: Phone,
  megaphone: Megaphone,
  lightbulb: Lightbulb,
  flaskConical: FlaskConical,
  monitor: Monitor,
  palette: Palette,
  trophy: Award,
  medal: Trophy,
  heartPulse: HeartPulse,
  stethoscope: Stethoscope,
  handshake: Handshake,
  piggyBank: PiggyBank,
  globe: Globe,
  layers: Layers,
  wrench: Wrench,
};

export function resolveIcon(id: string | undefined, fallback: LucideIcon = Users): LucideIcon {
  if (!id) return fallback;
  return iconOptions[id] ?? fallback;
}
